spring:
  application:
    name: spf-msa-customer-management
  header:
    channel: digital
    medium: web  
  flyway:
      enabled: true
      baseline-on-migrate: true
      locations:
          "classpath:db/migration"
      sql-migration-suffixes:
          ".sql"
      sql-migration-prefix:
          V
      sql-migration-separator:
          "__"

 



 




 
